SET NAMES UTF8;   #设置客户端连接服务器编码utf8
DROP DATABASE IF EXISTS pet;   #如果存在pet数据库就删除
CREATE DATABASE pet CHARSET=UTF8;  #创建数据库并设置编码为UTF8
USE pet;    #使用pet数据库

/**************************************************************用户信息表*******************************************************************/
CREATE TABLE pet_user(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(32),
    upwd VARCHAR(32),
    email VARCHAR(64),
    phone VARCHAR(16),
    avatar VARCHAR(128),        #头像图片路径
    user_name VARCHAR(32),      #用户名
    gender INT                  #性别  0-女  1-男
);


/**用户信息**/
INSERT INTO pet_user VALUES
(NULL, 'dingding', '123456', 'ding@qq.com', '13501234567', 'img/avatar/default.png', '丁伟', '1'),
(NULL, 'dangdang', '123456', 'dang@qq.com', '13501234568', 'img/avatar/default.png', '林当', '1'),
(NULL, 'doudou', '123456', 'dou@qq.com', '13501234569', 'img/avatar/default.png', '窦志强', '1'),
(NULL, 'yaya', '123456', 'ya@qq.com', '13501234560', 'img/avatar/default.png', '秦小雅', '0');
/*****************************************************************首页轮播广告商品*************************************************************/
CREATE TABLE pet_index_carlusel(
    cid INT PRIMARY KEY AUTO_INCREMENT, #商品cid
    img VARCHAR(128),                   #图片
    title VARCHAR(64),                  #商品描述
    href VARCHAR(128)                   #商品链接
);


INSERT INTO pet_index_carlusel VALUES
(NULL, 'images/index/ca1.jpg','轮播广告商品1',''),
(NULL, 'images/index/ca2.jpg','轮播广告商品2',''),
(NULL, 'images/index/ca3.jpg','轮播广告商品3',''),
(NULL, 'images/index/ca4.jpg','轮播广告商品4','');


/*****************************************************************宠物物品按作用分类***************************************************************/
CREATE TABLE pet_laptop_family(
  fid INT PRIMARY KEY AUTO_INCREMENT,
  fname VARCHAR(32)
);

INSERT INTO pet_laptop_family VALUES
(NULL,'宠物窝具'),
(NULL,'宠物服装'),
(NULL,'美容清洁'),
(NULL,'美味零食'),
(NULL,'宠物玩具');


/********************************************************************宠物用品*********************************************************************/
CREATE TABLE pet_laptop(
    lid INT PRIMARY KEY AUTO_INCREMENT,
    family_id INT,              #所属型号家族编号
    title VARCHAR(128),         #主标题
    price DECIMAL(10,2),        #价格
    promise VARCHAR(64),        #服务承诺
    spec VARCHAR(64),           #规格/颜色
    lname VARCHAR(32),          #商品名称
    texture VARCHAR(32),        #材质
    details VARCHAR(1024),      #产品详细说明
    shelf_time BIGINT,          #上架时间
    sold_count INT,             #已售出的数量
    is_onsale BOOLEAN           #是否促销中
);
/****************************************************************插入宠物用品***********************************************************************/
INSERT INTO pet_laptop VALUES
(null,1,'狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'蒙古包小狗窝可拆洗冬天保暖泰迪狗狗宠物用品小型犬房子猫咪猫窝(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗萨摩耶大型犬宠物垫子哈士奇耐咬柯基狗床狗狗沙发冬天(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'蒙古包小狗窝可拆洗冬天保暖泰迪狗狗宠物用品小型犬房子猫咪猫窝(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗萨摩耶大型犬宠物垫子哈士奇耐咬柯基狗床狗狗沙发冬天(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'金毛狗窝中型大型犬可拆洗宠物狗狗用品耐咬大号狗床垫子冬天保暖(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'蒙古包小狗窝可拆洗冬天保暖泰迪狗狗宠物用品小型犬房子猫咪猫窝(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗萨摩耶大型犬宠物垫子哈士奇耐咬柯基狗床狗狗沙发冬天(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'金毛狗窝中型大型犬可拆洗宠物狗狗用品耐咬大号狗床垫子冬天保暖(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗萨摩耶大型犬宠物垫子哈士奇耐咬柯基狗床狗狗沙发冬天(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'金毛狗窝中型大型犬可拆洗宠物狗狗用品耐咬大号狗床垫子冬天保暖(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'金毛狗窝中型大型犬可拆洗宠物狗狗用品耐咬大号狗床垫子冬天保暖(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗萨摩耶大型犬宠物垫子哈士奇耐咬柯基狗床狗狗沙发冬天(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'金毛狗窝中型大型犬可拆洗宠物狗狗用品耐咬大号狗床垫子冬天保暖(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗萨摩耶大型犬宠物垫子哈士奇耐咬柯基狗床狗狗沙发冬天(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'金毛狗窝中型大型犬可拆洗宠物狗狗用品耐咬大号狗床垫子冬天保暖(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'狗窝可拆洗萨摩耶大型犬宠物垫子哈士奇耐咬柯基狗床狗狗沙发冬天(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'宠物凉席狗狗冰垫夏季狗窝夏天 泰迪金毛狗笼垫子大型犬床垫草席(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,1,'金毛狗窝中型大型犬可拆洗宠物狗狗用品耐咬大号狗床垫子冬天保暖(窝具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服泰迪比熊吉娃娃博美柯基猫咪小型幼犬宠物小狗四脚秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服泰迪比熊贵宾吉娃娃小鹿犬博美棉衣小狗小型犬宠物秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'宠物袜子小狗鞋子泰迪金毛萨摩耶比熊博美大型犬狗狗脚套防滑防水(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗生理裤大型犬防骚扰宠物月经裤母狗姨妈巾金毛大狗卫生安全裤(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服秋冬装泰迪比熊吉娃娃雪纳瑞小鹿犬博美猫咪柯基宠物卫衣(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'金毛狗狗衣服大狗拉布拉多萨摩耶哈士奇柴犬中型大型犬宠物秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服秋冬装泰迪比熊吉娃娃雪纳瑞小鹿犬博美猫咪柯基宠物卫衣(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服泰迪比熊吉娃娃博美柯基猫咪小型幼犬宠物小狗四脚秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服泰迪比熊贵宾吉娃娃小鹿犬博美棉衣小狗小型犬宠物秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'宠物袜子小狗鞋子泰迪金毛萨摩耶比熊博美大型犬狗狗脚套防滑防水(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗生理裤大型犬防骚扰宠物月经裤母狗姨妈巾金毛大狗卫生安全裤(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服秋冬装泰迪比熊吉娃娃雪纳瑞小鹿犬博美猫咪柯基宠物卫衣(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'金毛狗狗衣服大狗拉布拉多萨摩耶哈士奇柴犬中型大型犬宠物秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服秋冬装泰迪比熊吉娃娃雪纳瑞小鹿犬博美猫咪柯基宠物卫衣(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服泰迪比熊吉娃娃博美柯基猫咪小型幼犬宠物小狗四脚秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服泰迪比熊贵宾吉娃娃小鹿犬博美棉衣小狗小型犬宠物秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'宠物袜子小狗鞋子泰迪金毛萨摩耶比熊博美大型犬狗狗脚套防滑防水(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗生理裤大型犬防骚扰宠物月经裤母狗姨妈巾金毛大狗卫生安全裤(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服秋冬装泰迪比熊吉娃娃雪纳瑞小鹿犬博美猫咪柯基宠物卫衣(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'金毛狗狗衣服大狗拉布拉多萨摩耶哈士奇柴犬中型大型犬宠物秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服秋冬装泰迪比熊吉娃娃雪纳瑞小鹿犬博美猫咪柯基宠物卫衣(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服泰迪比熊吉娃娃博美柯基猫咪小型幼犬宠物小狗四脚秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服泰迪比熊贵宾吉娃娃小鹿犬博美棉衣小狗小型犬宠物秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'宠物袜子小狗鞋子泰迪金毛萨摩耶比熊博美大型犬狗狗脚套防滑防水(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗生理裤大型犬防骚扰宠物月经裤母狗姨妈巾金毛大狗卫生安全裤(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服秋冬装泰迪比熊吉娃娃雪纳瑞小鹿犬博美猫咪柯基宠物卫衣(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'金毛狗狗衣服大狗拉布拉多萨摩耶哈士奇柴犬中型大型犬宠物秋冬装(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,2,'狗狗衣服秋冬装泰迪比熊吉娃娃雪纳瑞小鹿犬博美猫咪柯基宠物卫衣(服装)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'泰迪狗狗沐浴露白毛除臭止痒贵宾红棕专用宠物博美香波洗澡液用品(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗尿片小狗用尿垫大号金毛用品幼犬猫尿不湿加厚100片除臭泰迪(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗除臭剂宠物去味消毒液泰迪金毛香水环境喷雾除味剂持久去尿味(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗沐浴露萨摩耶博美比熊白毛专用去泪痕洗澡液除臭美白去黄用品(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'泰迪狗狗沐浴露白毛除臭止痒贵宾红棕专用宠物博美香波洗澡液用品(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗尿片小狗用尿垫大号金毛用品幼犬猫尿不湿加厚100片除臭泰迪(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗除臭剂宠物去味消毒液泰迪金毛香水环境喷雾除味剂持久去尿味(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗沐浴露萨摩耶博美比熊白毛专用去泪痕洗澡液除臭美白去黄用品(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗尿片小狗用尿垫大号金毛用品幼犬猫尿不湿加厚100片除臭泰迪(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗除臭剂宠物去味消毒液泰迪金毛香水环境喷雾除味剂持久去尿味(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,3,'狗狗沐浴露萨摩耶博美比熊白毛专用去泪痕洗澡液除臭美白去黄用品(清洁)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物零食牛肉棒肉干泰迪哈士奇幼犬狗狗吃的零食牛肉条补钙磨牙棒(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物零食牛肉棒肉干泰迪哈士奇幼犬狗狗吃的零食牛肉条补钙磨牙棒(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'狗零食狗狗磨牙棒训狗幼犬泰迪金毛宠物零食鳕鱼鸡肉洁齿骨狗咬胶(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物香肠狗狗零食狗狗火腿肠多种口味香肠宠物狗狗训练香肠10支装(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物零食牛肉棒肉干泰迪哈士奇幼犬狗狗吃的零食牛肉条补钙磨牙棒(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物零食牛肉棒肉干泰迪哈士奇幼犬狗狗吃的零食牛肉条补钙磨牙棒(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'狗零食狗狗磨牙棒训狗幼犬泰迪金毛宠物零食鳕鱼鸡肉洁齿骨狗咬胶(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物香肠狗狗零食狗狗火腿肠多种口味香肠宠物狗狗训练香肠10支装(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物零食牛肉棒肉干泰迪哈士奇幼犬狗狗吃的零食牛肉条补钙磨牙棒(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物零食牛肉棒肉干泰迪哈士奇幼犬狗狗吃的零食牛肉条补钙磨牙棒(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'狗零食狗狗磨牙棒训狗幼犬泰迪金毛宠物零食鳕鱼鸡肉洁齿骨狗咬胶(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物香肠狗狗零食狗狗火腿肠多种口味香肠宠物狗狗训练香肠10支装(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物零食牛肉棒肉干泰迪哈士奇幼犬狗狗吃的零食牛肉条补钙磨牙棒(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物零食牛肉棒肉干泰迪哈士奇幼犬狗狗吃的零食牛肉条补钙磨牙棒(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'狗零食狗狗磨牙棒训狗幼犬泰迪金毛宠物零食鳕鱼鸡肉洁齿骨狗咬胶(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,4,'宠物香肠狗狗零食狗狗火腿肠多种口味香肠宠物狗狗训练香肠10支装(零食)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,5,'宠物玩具猫狗狗发声玩具 磨牙耐咬球小型犬 七彩响铃球 泰迪金毛(玩具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,5,'狗狗玩具发声磨牙泰迪博美比熊小型犬金毛幼犬尖叫鸡互动宠物用品(玩具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,5,'狗狗玩具发声磨牙泰迪博美比熊小型犬金毛幼犬尖叫鸡互动宠物用品(玩具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,5,'宠物咬绳泰迪狗狗洁齿玩具 狗狗球狗咬绳磨牙耐咬宠物玩具 耐咬球(玩具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,5,'狗狗玩具磨牙发声泰迪比熊博美小狗幼犬金毛互动益智训练宠物用品(玩具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true),
(null,5,'狗狗玩具咬绳玩具球泰迪小狗金毛幼犬大型犬磨牙耐咬绳结宠物用品(玩具)',89.99,'*退货补运费 *30天无忧退货 *48小时快速退款 *72小时发货','长30cm适合5斤内','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品','woju','狗窝可拆洗冬天保暖泰迪博美宠物小型中型大型犬金毛狗床狗狗用品',150123456789,2968,true);


/*****************************************************************宠物用品图片***************************************************************************/
CREATE TABLE pet_laptop_pic(
  pid INT PRIMARY KEY AUTO_INCREMENT,
  laptop_id INT,              #宠物商品编号
  sm VARCHAR(128),            #小图片路径
  md VARCHAR(128),            #中图片路径
  lg VARCHAR(128)             #大图片路径
);
INSERT INTO pet_laptop_pic VALUES
(NULL, 1, 'images/house/sm/product1.jpg','images/house/md/product1.jpg','images/house/lg/product1.jpg'),
(NULL, 1, 'images/house/sm/product2.jpg','images/house/md/product2.jpg','images/house/lg/product2.jpg'),
(NULL, 1, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 1, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 1, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 1, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 1, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 2, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 2, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 2, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 2, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 2, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 2, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 3, 'images/house/sm/product14.jpg','images/house/md/product14.jpg','images/house/lg/product14.jpg'),
(NULL, 3, 'images/house/sm/product15.jpg','images/house/md/product15.jpg','images/house/lg/product15.jpg'),
(NULL, 3, 'images/house/sm/product16.jpg','images/house/md/product16.jpg','images/house/lg/product16.jpg'),
(NULL, 3, 'images/house/sm/product17.jpg','images/house/md/product17.jpg','images/house/lg/product17.jpg'),
(NULL, 3, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 4, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 4, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 4, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 4, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 4, 'images/house/sm/product14.jpg','images/house/md/product14.jpg','images/house/lg/product14.jpg'),
(NULL, 5, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 5, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 5, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 5, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 5, 'images/house/sm/product14.jpg','images/house/md/product14.jpg','images/house/lg/product14.jpg'),
(NULL, 5, 'images/house/sm/product15.jpg','images/house/md/product15.jpg','images/house/lg/product15.jpg'),
(NULL, 6, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 6, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 6, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 6, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 7, 'images/house/sm/product2.jpg','images/house/md/product2.jpg','images/house/lg/product2.jpg'),
(NULL, 7, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 7, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 7, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 7, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 7, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 7, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 8, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 8, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 8, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 8, 'images/house/sm/product14.jpg','images/house/md/product14.jpg','images/house/lg/product14.jpg'),
(NULL, 8, 'images/house/sm/product15.jpg','images/house/md/product15.jpg','images/house/lg/product15.jpg'),
(NULL, 9, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 9, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 9, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 10, 'images/house/sm/product16.jpg','images/house/md/product16.jpg','images/house/lg/product16.jpg'),
(NULL, 10, 'images/house/sm/product17.jpg','images/house/md/product17.jpg','images/house/lg/product17.jpg'),
(NULL, 10, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 10, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 10, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 10, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 11, 'images/house/sm/product1.jpg','images/house/md/product1.jpg','images/house/lg/product1.jpg'),
(NULL, 11, 'images/house/sm/product2.jpg','images/house/md/product2.jpg','images/house/lg/product2.jpg'),
(NULL, 11, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 11, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 11, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 11, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 11, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 12, 'images/house/sm/product2.jpg','images/house/md/product2.jpg','images/house/lg/product2.jpg'),
(NULL, 12, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 12, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 12, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 12, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 12, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 13, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 13, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 13, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 13, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 13, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 14, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 14, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 14, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 14, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 14, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 15, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 15, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 15, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 15, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 15, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 16, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 16, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 16, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 16, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 17, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 17, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 17, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 17, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 17, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 18, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 18, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 18, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 18, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 18, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 19, 'images/house/sm/product7.jpg','images/house/md/product7.jpg','images/house/lg/product7.jpg'),
(NULL, 19, 'images/house/sm/product3.jpg','images/house/md/product3.jpg','images/house/lg/product3.jpg'),
(NULL, 19, 'images/house/sm/product4.jpg','images/house/md/product4.jpg','images/house/lg/product4.jpg'),
(NULL, 19, 'images/house/sm/product5.jpg','images/house/md/product5.jpg','images/house/lg/product5.jpg'),
(NULL, 19, 'images/house/sm/product6.jpg','images/house/md/product6.jpg','images/house/lg/product6.jpg'),
(NULL, 20, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 20, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 20, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 20, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 20, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 20, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 21, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 21, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 21, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 21, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 21, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 21, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 22, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 22, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 22, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 22, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 22, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 22, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 23, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 23, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 23, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 23, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 23, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 24, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 24, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 24, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 24, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 24, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 24, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 25, 'images/house/sm/product13.jpg','images/house/md/product13.jpg','images/house/lg/product13.jpg'),
(NULL, 25, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 25, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 25, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 25, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 25, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 26, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 26, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 26, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 26, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 26, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 27, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 27, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 27, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 27, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 27, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 28, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 28, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 28, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 28, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 28, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 29, 'images/house/sm/product12.jpg','images/house/md/product12.jpg','images/house/lg/product12.jpg'),
(NULL, 29, 'images/house/sm/product11.jpg','images/house/md/product11.jpg','images/house/lg/product11.jpg'),
(NULL, 29, 'images/house/sm/product8.jpg','images/house/md/product8.jpg','images/house/lg/product8.jpg'),
(NULL, 29, 'images/house/sm/product9.jpg','images/house/md/product9.jpg','images/house/lg/product9.jpg'),
(NULL, 29, 'images/house/sm/product10.jpg','images/house/md/product10.jpg','images/house/lg/product10.jpg'),
(NULL, 30, 'images/house/sm/product14.jpg','images/house/md/product14.jpg','images/house/lg/product14.jpg'),
(NULL, 30, 'images/house/sm/product15.jpg','images/house/md/product15.jpg','images/house/lg/product15.jpg'),
(NULL, 30, 'images/house/sm/product16.jpg','images/house/md/product16.jpg','images/house/lg/product16.jpg'),
(NULL, 30, 'images/house/sm/product17.jpg','images/house/md/product17.jpg','images/house/lg/product17.jpg'),
(NULL, 30, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 31, 'images/house/sm/product15.jpg','images/house/md/product15.jpg','images/house/lg/product15.jpg'),
(NULL, 31, 'images/house/sm/product16.jpg','images/house/md/product16.jpg','images/house/lg/product16.jpg'),
(NULL, 31, 'images/house/sm/product17.jpg','images/house/md/product17.jpg','images/house/lg/product17.jpg'),
(NULL, 31, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 32, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 32, 'images/house/sm/product14.jpg','images/house/md/product14.jpg','images/house/lg/product14.jpg'),
(NULL, 32, 'images/house/sm/product15.jpg','images/house/md/product15.jpg','images/house/lg/product15.jpg'),
(NULL, 32, 'images/house/sm/product16.jpg','images/house/md/product16.jpg','images/house/lg/product16.jpg'),
(NULL, 32, 'images/house/sm/product17.jpg','images/house/md/product17.jpg','images/house/lg/product17.jpg'),
(NULL, 33, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 33, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 33, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 33, 'images/house/sm/product18.jpg','images/house/md/product18.jpg','images/house/lg/product18.jpg'),
(NULL, 34, 'images/cloth/sm/product1.jpg','images/cloth/md/product1.jpg','images/cloth/lg/product1.jpg'),
(NULL, 34, 'images/cloth/sm/product2.jpg','images/cloth/md/product2.jpg','images/cloth/lg/product2.jpg'),
(NULL, 34, 'images/cloth/sm/product3.jpg','images/cloth/md/product3.jpg','images/cloth/lg/product3.jpg'),
(NULL, 34, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 34, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 34, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 34, 'images/cloth/sm/product7.jpg','images/cloth/md/product7.jpg','images/cloth/lg/product7.jpg'),
(NULL, 35, 'images/cloth/sm/product8.jpg','images/cloth/md/product8.jpg','images/cloth/lg/product8.jpg'),
(NULL, 35, 'images/cloth/sm/product9.jpg','images/cloth/md/product9.jpg','images/cloth/lg/product9.jpg'),
(NULL, 35, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 35, 'images/cloth/sm/product11.jpg','images/cloth/md/product11.jpg','images/cloth/lg/product11.jpg'),
(NULL, 35, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 35, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 36, 'images/cloth/sm/product14.jpg','images/cloth/md/product14.jpg','images/cloth/lg/product14.jpg'),
(NULL, 36, 'images/cloth/sm/product15.jpg','images/cloth/md/product15.jpg','images/cloth/lg/product15.jpg'),
(NULL, 36, 'images/cloth/sm/product16.jpg','images/cloth/md/product16.jpg','images/cloth/lg/product16.jpg'),
(NULL, 36, 'images/cloth/sm/product17.jpg','images/cloth/md/product17.jpg','images/cloth/lg/product17.jpg'),
(NULL, 36, 'images/cloth/sm/product18.jpg','images/cloth/md/product18.jpg','images/cloth/lg/product18.jpg'),
(NULL, 37, 'images/cloth/sm/product17.jpg','images/cloth/md/product17.jpg','images/cloth/lg/product17.jpg'),
(NULL, 37, 'images/cloth/sm/product18.jpg','images/cloth/md/product18.jpg','images/cloth/lg/product18.jpg'),
(NULL, 37, 'images/cloth/sm/product19.jpg','images/cloth/md/product19.jpg','images/cloth/lg/product19.jpg'),
(NULL, 37, 'images/cloth/sm/product20.jpg','images/cloth/md/product20.jpg','images/cloth/lg/product20.jpg'),
(NULL, 38, 'images/cloth/sm/product18.jpg','images/cloth/md/product18.jpg','images/cloth/lg/product18.jpg'),
(NULL, 38, 'images/cloth/sm/product17.jpg','images/cloth/md/product17.jpg','images/cloth/lg/product17.jpg'),
(NULL, 38, 'images/cloth/sm/product18.jpg','images/cloth/md/product18.jpg','images/cloth/lg/product18.jpg'),
(NULL, 38, 'images/cloth/sm/product19.jpg','images/cloth/md/product19.jpg','images/cloth/lg/product19.jpg'),
(NULL, 38, 'images/cloth/sm/product20.jpg','images/cloth/md/product20.jpg','images/cloth/lg/product20.jpg'),
(NULL, 39, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 39, 'images/cloth/sm/product11.jpg','images/cloth/md/product11.jpg','images/cloth/lg/product11.jpg'),
(NULL, 39, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 39, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 39, 'images/cloth/sm/product14.jpg','images/cloth/md/product14.jpg','images/cloth/lg/product14.jpg'),
(NULL, 40, 'images/cloth/sm/product9.jpg','images/cloth/md/product9.jpg','images/cloth/lg/product9.jpg'),
(NULL, 40, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 40, 'images/cloth/sm/product11.jpg','images/cloth/md/product11.jpg','images/cloth/lg/product11.jpg'),
(NULL, 40, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 40, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 41, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 41, 'images/cloth/sm/product11.jpg','images/cloth/md/product11.jpg','images/cloth/lg/product11.jpg'),
(NULL, 41, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 41, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 42, 'images/cloth/sm/product1.jpg','images/cloth/md/product1.jpg','images/cloth/lg/product1.jpg'),
(NULL, 42, 'images/cloth/sm/product2.jpg','images/cloth/md/product2.jpg','images/cloth/lg/product2.jpg'),
(NULL, 42, 'images/cloth/sm/product3.jpg','images/cloth/md/product3.jpg','images/cloth/lg/product3.jpg'),
(NULL, 42, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 42, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 42, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 43, 'images/cloth/sm/product2.jpg','images/cloth/md/product2.jpg','images/cloth/lg/product2.jpg'),
(NULL, 43, 'images/cloth/sm/product3.jpg','images/cloth/md/product3.jpg','images/cloth/lg/product3.jpg'),
(NULL, 43, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 43, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 43, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 44, 'images/cloth/sm/product3.jpg','images/cloth/md/product3.jpg','images/cloth/lg/product3.jpg'),
(NULL, 44, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 44, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 44, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 45, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 45, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 45, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 46, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 46, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 46, 'images/cloth/sm/product14.jpg','images/cloth/md/product14.jpg','images/cloth/lg/product14.jpg'),
(NULL, 46, 'images/cloth/sm/product9.jpg','images/cloth/md/product9.jpg','images/cloth/lg/product9.jpg'),
(NULL, 46, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 47, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 47, 'images/cloth/sm/product14.jpg','images/cloth/md/product14.jpg','images/cloth/lg/product14.jpg'),
(NULL, 47, 'images/cloth/sm/product9.jpg','images/cloth/md/product9.jpg','images/cloth/lg/product9.jpg'),
(NULL, 47, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 48, 'images/cloth/sm/product14.jpg','images/cloth/md/product14.jpg','images/cloth/lg/product14.jpg'),
(NULL, 48, 'images/cloth/sm/product9.jpg','images/cloth/md/product9.jpg','images/cloth/lg/product9.jpg'),
(NULL, 48, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 49, 'images/cloth/sm/product9.jpg','images/cloth/md/product9.jpg','images/cloth/lg/product9.jpg'),
(NULL, 49, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 50, 'images/cloth/sm/product11.jpg','images/cloth/md/product11.jpg','images/cloth/lg/product11.jpg'),
(NULL, 50, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 50, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 50, 'images/cloth/sm/product1.jpg','images/cloth/md/product1.jpg','images/cloth/lg/product1.jpg'),
(NULL, 50, 'images/cloth/sm/product2.jpg','images/cloth/md/product2.jpg','images/cloth/lg/product2.jpg'),
(NULL, 51, 'images/cloth/sm/product20.jpg','images/cloth/md/product20.jpg','images/cloth/lg/product20.jpg'),
(NULL, 51, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 51, 'images/cloth/sm/product11.jpg','images/cloth/md/product11.jpg','images/cloth/lg/product11.jpg'),
(NULL, 51, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 51, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 52, 'images/cloth/sm/product10.jpg','images/cloth/md/product10.jpg','images/cloth/lg/product10.jpg'),
(NULL, 52, 'images/cloth/sm/product11.jpg','images/cloth/md/product11.jpg','images/cloth/lg/product11.jpg'),
(NULL, 52, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 52, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 53, 'images/cloth/sm/product11.jpg','images/cloth/md/product11.jpg','images/cloth/lg/product11.jpg'),
(NULL, 53, 'images/cloth/sm/product12.jpg','images/cloth/md/product12.jpg','images/cloth/lg/product12.jpg'),
(NULL, 53, 'images/cloth/sm/product13.jpg','images/cloth/md/product13.jpg','images/cloth/lg/product13.jpg'),
(NULL, 54, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 54, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 54, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 54, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 54, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 54, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 55, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 55, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 55, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 55, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 55, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 56, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 56, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 56, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 56, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 57, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 57, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 57, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 58, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 58, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 59, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 59, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 59, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 59, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 59, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 60, 'images/cloth/sm/product4.jpg','images/cloth/md/product4.jpg','images/cloth/lg/product4.jpg'),
(NULL, 60, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 60, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 60, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 61, 'images/cloth/sm/product5.jpg','images/cloth/md/product5.jpg','images/cloth/lg/product5.jpg'),
(NULL, 61, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 61, 'images/cloth/sm/product6.jpg','images/cloth/md/product6.jpg','images/cloth/lg/product6.jpg'),
(NULL, 62, 'images/clean/sm/product1.jpg','images/clean/md/product1.jpg','images/clean/lg/product1.jpg'),
(NULL, 62, 'images/clean/sm/product2.jpg','images/clean/md/product2.jpg','images/clean/lg/product2.jpg'),
(NULL, 62, 'images/clean/sm/product3.jpg','images/clean/md/product3.jpg','images/clean/lg/product3.jpg'),
(NULL, 62, 'images/clean/sm/product4.jpg','images/clean/md/product4.jpg','images/clean/lg/product4.jpg'),
(NULL, 62, 'images/clean/sm/product5.jpg','images/clean/md/product5.jpg','images/clean/lg/product5.jpg'),
(NULL, 62, 'images/clean/sm/product6.jpg','images/clean/md/product6.jpg','images/clean/lg/product6.jpg'),
(NULL, 62, 'images/clean/sm/product7.jpg','images/clean/md/product7.jpg','images/clean/lg/product7.jpg'),
(NULL, 63, 'images/clean/sm/product8.jpg','images/clean/md/product8.jpg','images/clean/lg/product8.jpg'),
(NULL, 63, 'images/clean/sm/product9.jpg','images/clean/md/product9.jpg','images/clean/lg/product9.jpg'),
(NULL, 63, 'images/clean/sm/product10.jpg','images/clean/md/product10.jpg','images/clean/lg/product10.jpg'),
(NULL, 63, 'images/clean/sm/product11.jpg','images/clean/md/product11.jpg','images/clean/lg/product11.jpg'),
(NULL, 63, 'images/clean/sm/product12.jpg','images/clean/md/product12.jpg','images/clean/lg/product12.jpg'),
(NULL, 63, 'images/clean/sm/product13.jpg','images/clean/md/product13.jpg','images/clean/lg/product13.jpg'),
(NULL, 64, 'images/clean/sm/product2.jpg','images/clean/md/product2.jpg','images/clean/lg/product2.jpg'),
(NULL, 64, 'images/clean/sm/product3.jpg','images/clean/md/product3.jpg','images/clean/lg/product3.jpg'),
(NULL, 64, 'images/clean/sm/product4.jpg','images/clean/md/product4.jpg','images/clean/lg/product4.jpg'),
(NULL, 64, 'images/clean/sm/product5.jpg','images/clean/md/product5.jpg','images/clean/lg/product5.jpg'),
(NULL, 64, 'images/clean/sm/product6.jpg','images/clean/md/product6.jpg','images/clean/lg/product6.jpg'),
(NULL, 64, 'images/clean/sm/product7.jpg','images/clean/md/product7.jpg','images/clean/lg/product7.jpg'),
(NULL, 65, 'images/clean/sm/product3.jpg','images/clean/md/product3.jpg','images/clean/lg/product3.jpg'),
(NULL, 65, 'images/clean/sm/product4.jpg','images/clean/md/product4.jpg','images/clean/lg/product4.jpg'),
(NULL, 65, 'images/clean/sm/product5.jpg','images/clean/md/product5.jpg','images/clean/lg/product5.jpg'),
(NULL, 65, 'images/clean/sm/product6.jpg','images/clean/md/product6.jpg','images/clean/lg/product6.jpg'),
(NULL, 65, 'images/clean/sm/product7.jpg','images/clean/md/product7.jpg','images/clean/lg/product7.jpg'),
(NULL, 66, 'images/clean/sm/product4.jpg','images/clean/md/product4.jpg','images/clean/lg/product4.jpg'),
(NULL, 66, 'images/clean/sm/product5.jpg','images/clean/md/product5.jpg','images/clean/lg/product5.jpg'),
(NULL, 66, 'images/clean/sm/product6.jpg','images/clean/md/product6.jpg','images/clean/lg/product6.jpg'),
(NULL, 66, 'images/clean/sm/product7.jpg','images/clean/md/product7.jpg','images/clean/lg/product7.jpg'),
(NULL, 67, 'images/clean/sm/product5.jpg','images/clean/md/product5.jpg','images/clean/lg/product5.jpg'),
(NULL, 67, 'images/clean/sm/product6.jpg','images/clean/md/product6.jpg','images/clean/lg/product6.jpg'),
(NULL, 67, 'images/clean/sm/product7.jpg','images/clean/md/product7.jpg','images/clean/lg/product7.jpg'),
(NULL, 68, 'images/clean/sm/product9.jpg','images/clean/md/product9.jpg','images/clean/lg/product9.jpg'),
(NULL, 68, 'images/clean/sm/product10.jpg','images/clean/md/product10.jpg','images/clean/lg/product10.jpg'),
(NULL, 68, 'images/clean/sm/product11.jpg','images/clean/md/product11.jpg','images/clean/lg/product11.jpg'),
(NULL, 68, 'images/clean/sm/product12.jpg','images/clean/md/product12.jpg','images/clean/lg/product12.jpg'),
(NULL, 68, 'images/clean/sm/product13.jpg','images/clean/md/product13.jpg','images/clean/lg/product13.jpg'),
(NULL, 69, 'images/clean/sm/product10.jpg','images/clean/md/product10.jpg','images/clean/lg/product10.jpg'),
(NULL, 69, 'images/clean/sm/product11.jpg','images/clean/md/product11.jpg','images/clean/lg/product11.jpg'),
(NULL, 69, 'images/clean/sm/product12.jpg','images/clean/md/product12.jpg','images/clean/lg/product12.jpg'),
(NULL, 69, 'images/clean/sm/product13.jpg','images/clean/md/product13.jpg','images/clean/lg/product13.jpg'),
(NULL, 70, 'images/clean/sm/product3.jpg','images/clean/md/product3.jpg','images/clean/lg/product3.jpg'),
(NULL, 70, 'images/clean/sm/product4.jpg','images/clean/md/product4.jpg','images/clean/lg/product4.jpg'),
(NULL, 70, 'images/clean/sm/product5.jpg','images/clean/md/product5.jpg','images/clean/lg/product5.jpg'),
(NULL, 70, 'images/clean/sm/product6.jpg','images/clean/md/product6.jpg','images/clean/lg/product6.jpg'),
(NULL, 70, 'images/clean/sm/product7.jpg','images/clean/md/product7.jpg','images/clean/lg/product7.jpg'),
(NULL, 71, 'images/clean/sm/product4.jpg','images/clean/md/product4.jpg','images/clean/lg/product4.jpg'),
(NULL, 71, 'images/clean/sm/product5.jpg','images/clean/md/product5.jpg','images/clean/lg/product5.jpg'),
(NULL, 71, 'images/clean/sm/product6.jpg','images/clean/md/product6.jpg','images/clean/lg/product6.jpg'),
(NULL, 71, 'images/clean/sm/product7.jpg','images/clean/md/product7.jpg','images/clean/lg/product7.jpg'),
(NULL, 72, 'images/clean/sm/product5.jpg','images/clean/md/product5.jpg','images/clean/lg/product5.jpg'),
(NULL, 72, 'images/clean/sm/product6.jpg','images/clean/md/product6.jpg','images/clean/lg/product6.jpg'),
(NULL, 72, 'images/clean/sm/product7.jpg','images/clean/md/product7.jpg','images/clean/lg/product7.jpg'),
(NULL, 73, 'images/food/sm/product1.jpg','images/food/md/product1.jpg','images/food/lg/product1.jpg'),
(NULL, 73, 'images/food/sm/product2.jpg','images/food/md/product2.jpg','images/food/lg/product2.jpg'),
(NULL, 73, 'images/food/sm/product3.jpg','images/food/md/product3.jpg','images/food/lg/product3.jpg'),
(NULL, 73, 'images/food/sm/product4.jpg','images/food/md/product4.jpg','images/food/lg/product4.jpg'),
(NULL, 73, 'images/food/sm/product5.jpg','images/food/md/product5.jpg','images/food/lg/product5.jpg'),
(NULL, 73, 'images/food/sm/product6.jpg','images/food/md/product6.jpg','images/food/lg/product6.jpg'),
(NULL, 73, 'images/food/sm/product7.jpg','images/food/md/product7.jpg','images/food/lg/product7.jpg'),
(NULL, 74, 'images/food/sm/product8.jpg','images/food/md/product8.jpg','images/food/lg/product8.jpg'),
(NULL, 74, 'images/food/sm/product9.jpg','images/food/md/product9.jpg','images/food/lg/product9.jpg'),
(NULL, 74, 'images/food/sm/product10.jpg','images/food/md/product10.jpg','images/food/lg/product10.jpg'),
(NULL, 74, 'images/food/sm/product11.jpg','images/food/md/product11.jpg','images/food/lg/product11.jpg'),
(NULL, 74, 'images/food/sm/product12.jpg','images/food/md/product12.jpg','images/food/lg/product12.jpg'),
(NULL, 74, 'images/food/sm/product13.jpg','images/food/md/product13.jpg','images/food/lg/product13.jpg'),
(NULL, 75, 'images/food/sm/product14.jpg','images/food/md/product14.jpg','images/food/lg/product14.jpg'),
(NULL, 75, 'images/food/sm/product15.jpg','images/food/md/product15.jpg','images/food/lg/product15.jpg'),
(NULL, 75, 'images/food/sm/product16.jpg','images/food/md/product16.jpg','images/food/lg/product16.jpg'),
(NULL, 76, 'images/food/sm/product2.jpg','images/food/md/product2.jpg','images/food/lg/product2.jpg'),
(NULL, 76, 'images/food/sm/product3.jpg','images/food/md/product3.jpg','images/food/lg/product3.jpg'),
(NULL, 76, 'images/food/sm/product4.jpg','images/food/md/product4.jpg','images/food/lg/product4.jpg'),
(NULL, 76, 'images/food/sm/product5.jpg','images/food/md/product5.jpg','images/food/lg/product5.jpg'),
(NULL, 77, 'images/food/sm/product6.jpg','images/food/md/product6.jpg','images/food/lg/product6.jpg'),
(NULL, 77, 'images/food/sm/product7.jpg','images/food/md/product7.jpg','images/food/lg/product7.jpg'),
(NULL, 77, 'images/food/sm/product8.jpg','images/food/md/product8.jpg','images/food/lg/product8.jpg'),
(NULL, 77, 'images/food/sm/product9.jpg','images/food/md/product9.jpg','images/food/lg/product9.jpg'),
(NULL, 78, 'images/food/sm/product10.jpg','images/food/md/product10.jpg','images/food/lg/product10.jpg'),
(NULL, 78, 'images/food/sm/product11.jpg','images/food/md/product11.jpg','images/food/lg/product11.jpg'),
(NULL, 78, 'images/food/sm/product12.jpg','images/food/md/product12.jpg','images/food/lg/product12.jpg'),
(NULL, 78, 'images/food/sm/product13.jpg','images/food/md/product13.jpg','images/food/lg/product13.jpg'),
(NULL, 78, 'images/food/sm/product14.jpg','images/food/md/product14.jpg','images/food/lg/product14.jpg'),
(NULL, 79, 'images/food/sm/product15.jpg','images/food/md/product15.jpg','images/food/lg/product15.jpg'),
(NULL, 79, 'images/food/sm/product16.jpg','images/food/md/product16.jpg','images/food/lg/product16.jpg'),
(NULL, 79, 'images/food/sm/product2.jpg','images/food/md/product2.jpg','images/food/lg/product2.jpg'),
(NULL, 80, 'images/food/sm/product3.jpg','images/food/md/product3.jpg','images/food/lg/product3.jpg'),
(NULL, 80, 'images/food/sm/product4.jpg','images/food/md/product4.jpg','images/food/lg/product4.jpg'),
(NULL, 80, 'images/food/sm/product5.jpg','images/food/md/product5.jpg','images/food/lg/product5.jpg'),
(NULL, 80, 'images/food/sm/product6.jpg','images/food/md/product6.jpg','images/food/lg/product6.jpg'),
(NULL, 81, 'images/food/sm/product7.jpg','images/food/md/product7.jpg','images/food/lg/product7.jpg'),
(NULL, 81, 'images/food/sm/product8.jpg','images/food/md/product8.jpg','images/food/lg/product8.jpg'),
(NULL, 81, 'images/food/sm/product9.jpg','images/food/md/product9.jpg','images/food/lg/product9.jpg'),
(NULL, 81, 'images/food/sm/product10.jpg','images/food/md/product10.jpg','images/food/lg/product10.jpg'),
(NULL, 82, 'images/food/sm/product11.jpg','images/food/md/product11.jpg','images/food/lg/product11.jpg'),
(NULL, 82, 'images/food/sm/product12.jpg','images/food/md/product12.jpg','images/food/lg/product12.jpg'),
(NULL, 82, 'images/food/sm/product13.jpg','images/food/md/product13.jpg','images/food/lg/product13.jpg'),
(NULL, 82, 'images/food/sm/product14.jpg','images/food/md/product14.jpg','images/food/lg/product14.jpg'),
(NULL, 83, 'images/food/sm/product15.jpg','images/food/md/product15.jpg','images/food/lg/product15.jpg'),
(NULL, 83, 'images/food/sm/product16.jpg','images/food/md/product16.jpg','images/food/lg/product16.jpg'),
(NULL, 83, 'images/food/sm/product1.jpg','images/food/md/product1.jpg','images/food/lg/product1.jpg'),
(NULL, 83, 'images/food/sm/product2.jpg','images/food/md/product2.jpg','images/food/lg/product2.jpg'),
(NULL, 83, 'images/food/sm/product3.jpg','images/food/md/product3.jpg','images/food/lg/product3.jpg'),
(NULL, 84, 'images/food/sm/product4.jpg','images/food/md/product4.jpg','images/food/lg/product4.jpg'),
(NULL, 84, 'images/food/sm/product5.jpg','images/food/md/product5.jpg','images/food/lg/product5.jpg'),
(NULL, 84, 'images/food/sm/product6.jpg','images/food/md/product6.jpg','images/food/lg/product6.jpg'),
(NULL, 84, 'images/food/sm/product7.jpg','images/food/md/product7.jpg','images/food/lg/product7.jpg'),
(NULL, 84, 'images/food/sm/product8.jpg','images/food/md/product8.jpg','images/food/lg/product8.jpg'),
(NULL, 85, 'images/food/sm/product9.jpg','images/food/md/product9.jpg','images/food/lg/product9.jpg'),
(NULL, 85, 'images/food/sm/product10.jpg','images/food/md/product10.jpg','images/food/lg/product10.jpg'),
(NULL, 85, 'images/food/sm/product11.jpg','images/food/md/product11.jpg','images/food/lg/product11.jpg'),
(NULL, 85, 'images/food/sm/product12.jpg','images/food/md/product12.jpg','images/food/lg/product12.jpg'),
(NULL, 85, 'images/food/sm/product13.jpg','images/food/md/product13.jpg','images/food/lg/product13.jpg'),
(NULL, 85, 'images/food/sm/product14.jpg','images/food/md/product14.jpg','images/food/lg/product14.jpg'),
(NULL, 85, 'images/food/sm/product15.jpg','images/food/md/product15.jpg','images/food/lg/product15.jpg'),
(NULL, 86, 'images/food/sm/product16.jpg','images/food/md/product16.jpg','images/food/lg/product16.jpg'),
(NULL, 86, 'images/food/sm/product1.jpg','images/food/md/product1.jpg','images/food/lg/product1.jpg'),
(NULL, 86, 'images/food/sm/product2.jpg','images/food/md/product2.jpg','images/food/lg/product2.jpg'),
(NULL, 86, 'images/food/sm/product3.jpg','images/food/md/product3.jpg','images/food/lg/product3.jpg'),
(NULL, 87, 'images/food/sm/product4.jpg','images/food/md/product4.jpg','images/food/lg/product4.jpg'),
(NULL, 87, 'images/food/sm/product5.jpg','images/food/md/product5.jpg','images/food/lg/product5.jpg'),
(NULL, 87, 'images/food/sm/product6.jpg','images/food/md/product6.jpg','images/food/lg/product6.jpg'),
(NULL, 87, 'images/food/sm/product7.jpg','images/food/md/product7.jpg','images/food/lg/product7.jpg'),
(NULL, 87, 'images/food/sm/product8.jpg','images/food/md/product8.jpg','images/food/lg/product8.jpg'),
(NULL, 88, 'images/food/sm/product9.jpg','images/food/md/product9.jpg','images/food/lg/product9.jpg'),
(NULL, 88, 'images/food/sm/product10.jpg','images/food/md/product10.jpg','images/food/lg/product10.jpg'),
(NULL, 88, 'images/food/sm/product11.jpg','images/food/md/product11.jpg','images/food/lg/product11.jpg'),
(NULL, 88, 'images/food/sm/product12.jpg','images/food/md/product12.jpg','images/food/lg/product12.jpg'),
(NULL, 88, 'images/food/sm/product13.jpg','images/food/md/product13.jpg','images/food/lg/product13.jpg'),
(NULL, 89, 'images/toy/sm/product1.jpg','images/toy/md/product1.jpg','images/toy/lg/product1.jpg'),
(NULL, 89, 'images/toy/sm/product2.jpg','images/toy/md/product2.jpg','images/toy/lg/product2.jpg'),
(NULL, 89, 'images/toy/sm/product3.jpg','images/toy/md/product3.jpg','images/toy/lg/product3.jpg'),
(NULL, 89, 'images/toy/sm/product4.jpg','images/toy/md/product4.jpg','images/toy/lg/product4.jpg'),
(NULL, 89, 'images/toy/sm/product5.jpg','images/toy/md/product5.jpg','images/toy/lg/product5.jpg'),
(NULL, 90, 'images/toy/sm/product6.jpg','images/toy/md/product6.jpg','images/toy/lg/product6.jpg'),
(NULL, 90, 'images/toy/sm/product7.jpg','images/toy/md/product7.jpg','images/toy/lg/product7.jpg'),
(NULL, 90, 'images/toy/sm/product8.jpg','images/toy/md/product8.jpg','images/toy/lg/product8.jpg'),
(NULL, 90, 'images/toy/sm/product9.jpg','images/toy/md/product9.jpg','images/toy/lg/product9.jpg'),
(NULL, 90, 'images/toy/sm/product10.jpg','images/toy/md/product10.jpg','images/toy/lg/product10.jpg'),
(NULL, 91, 'images/toy/sm/product11.jpg','images/toy/md/product11.jpg','images/toy/lg/product11.jpg'),
(NULL, 91, 'images/toy/sm/product12.jpg','images/toy/md/product12.jpg','images/toy/lg/product12.jpg'),
(NULL, 91, 'images/toy/sm/product13.jpg','images/toy/md/product13.jpg','images/toy/lg/product13.jpg'),
(NULL, 91, 'images/toy/sm/product14.jpg','images/toy/md/product14.jpg','images/toy/lg/product14.jpg'),
(NULL, 91, 'images/toy/sm/product15.jpg','images/toy/md/product15.jpg','images/toy/lg/product15.jpg'),
(NULL, 91, 'images/toy/sm/product16.jpg','images/toy/md/product16.jpg','images/toy/lg/product16.jpg'),
(NULL, 91, 'images/toy/sm/product1.jpg','images/toy/md/product1.jpg','images/toy/lg/product1.jpg'),
(NULL, 92, 'images/toy/sm/product2.jpg','images/toy/md/product2.jpg','images/toy/lg/product2.jpg'),
(NULL, 92, 'images/toy/sm/product3.jpg','images/toy/md/product3.jpg','images/toy/lg/product3.jpg'),
(NULL, 92, 'images/toy/sm/product4.jpg','images/toy/md/product4.jpg','images/toy/lg/product4.jpg'),
(NULL, 92, 'images/toy/sm/product5.jpg','images/toy/md/product5.jpg','images/toy/lg/product5.jpg'),
(NULL, 92, 'images/toy/sm/product6.jpg','images/toy/md/product6.jpg','images/toy/lg/product6.jpg'),
(NULL, 92, 'images/toy/sm/product7.jpg','images/toy/md/product7.jpg','images/toy/lg/product7.jpg'),
(NULL, 93, 'images/toy/sm/product8.jpg','images/toy/md/product8.jpg','images/toy/lg/product8.jpg'),
(NULL, 93, 'images/toy/sm/product9.jpg','images/toy/md/product9.jpg','images/toy/lg/product9.jpg'),
(NULL, 93, 'images/toy/sm/product10.jpg','images/toy/md/product10.jpg','images/toy/lg/product10.jpg'),
(NULL, 93, 'images/toy/sm/product11.jpg','images/toy/md/product11.jpg','images/toy/lg/product11.jpg'),
(NULL, 93, 'images/toy/sm/product12.jpg','images/toy/md/product12.jpg','images/toy/lg/product12.jpg'),
(NULL, 93, 'images/toy/sm/product13.jpg','images/toy/md/product13.jpg','images/toy/lg/product13.jpg'),
(NULL, 93, 'images/toy/sm/product14.jpg','images/toy/md/product14.jpg','images/toy/lg/product14.jpg'),
(NULL, 94, 'images/toy/sm/product15.jpg','images/toy/md/product15.jpg','images/toy/lg/product15.jpg'),
(NULL, 94, 'images/toy/sm/product16.jpg','images/toy/md/product16.jpg','images/toy/lg/product16.jpg'),
(NULL, 94, 'images/toy/sm/product1.jpg','images/toy/md/product1.jpg','images/toy/lg/product1.jpg'),
(NULL, 94, 'images/toy/sm/product2.jpg','images/toy/md/product2.jpg','images/toy/lg/product2.jpg'),
(NULL, 94, 'images/toy/sm/product3.jpg','images/toy/md/product3.jpg','images/toy/lg/product3.jpg'),
(NULL, 94, 'images/toy/sm/product4.jpg','images/toy/md/product4.jpg','images/toy/lg/product4.jpg'),
(NULL, 94, 'images/toy/sm/product5.jpg','images/toy/md/product5.jpg','images/toy/lg/product5.jpg');

/********************************************************购物车条目***************************************************************************/
CREATE TABLE pet_shoppingcart_item(
  iid INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,      #用户编号
  product_id INT,   #商品编号
  count INT,        #购买数量
  is_checked BOOLEAN #是否已勾选，确定购买
);















